"use client";

import { useEffect } from "react";
import type { Lang } from "@/lib/i18n";

const replacements: Array<[string, string]> = [
  ["Local Admin", "المدير المحلي"],
  ["Local Reception", "الاستقبال المحلي"],
  ["Local Sales", "المبيعات المحلية"],
  ["Local Teacher", "المدرس المحلي"],
  ["Local", "محلي"],
  ["(admin)", "(مدير)"],
  ["(reception)", "(استقبال)"],
  ["(sales)", "(مبيعات)"],
  ["...Search", "بحث"],
  ["interactions this week", "متابعات هذا الأسبوع"],
  ["bookings this month", "حجوزات هذا الشهر"],
  ["Created Classes", "الفصول المنشأة"],
  ["Class name", "اسم الفصل"],
  ["Current Kapitel / chapter", "الكابيتل أو الوحدة الحالية"],
  ["Save Class", "حفظ الفصل"],
  ["Update Class", "تحديث الفصل"],
  ["Time, e.g. 18:00", "الوقت، مثل 18:00"],
  ["Tags, e.g. electric company, water company", "التصنيفات، مثل شركة الكهرباء، شركة المياه"],
  ["Payment comment or arrangement notes...", "تعليق السداد أو ملاحظات الاتفاق..."],
  ["Online / Offline", "أونلاين / أوفلاين"],
  ["Stopped at", "توقف عند"],
  ["Total sessions", "إجمالي الحصص"],
  ["Sessions completed", "الحصص المكتملة"],
  ["Sessions", "الحصص"],
  ["Status", "الحالة"],
  ["Finished", "منتهية"],
  ["Started", "بدأت"],
  ["Not started", "لم تبدأ"],
  ["Today", "اليوم"],
  ["Completed", "مكتملة"],
  ["Weekly schedule", "الجدول الأسبوعي"],
  ["Monday", "الاثنين"],
  ["Tuesday", "الثلاثاء"],
  ["Wednesday", "الأربعاء"],
  ["Thursday", "الخميس"],
  ["Friday", "الجمعة"],
  ["Saturday", "السبت"],
  ["Sunday", "الأحد"],
  ["Mon", "الاثنين"],
  ["Tue", "الثلاثاء"],
  ["Wed", "الأربعاء"],
  ["Thu", "الخميس"],
  ["Fri", "الجمعة"],
  ["Sat", "السبت"],
  ["Sun", "الأحد"],
  ["Arranged remaining payment with student.", "تم الاتفاق مع الطالب على موعد السداد المتبقي."],
  ["All levels", "كل المستويات"],
  ["All teachers", "كل المدرسين"],
  ["All statuses", "كل الحالات"],
  ["Online / offline", "أونلاين / أوفلاين"],
  ["All classes", "كل الفصول"],
  ["No class", "بدون فصل"],
  ["Payment Date", "تاريخ السداد"],
  ["Alert", "التنبيه"],
  ["Not Paid", "غير مدفوع"],
  ["Paid", "مدفوع"],
  ["Scheduled", "محدد الموعد"],
  ["scheduled", "محدد الموعد"],
  ["overdue", "متأخر"],
  ["due today", "مستحق اليوم"],
  ["active", "نشط"],
  ["online", "أونلاين"],
  ["offline", "أوفلاين"],
  ["paid", "مدفوع"],
  ["Present", "حاضر"],
  ["Absent", "غائب"],
  ["Late", "متأخر"],
  ["Excused", "بعذر"],
  ["Lead", "عميل محتمل"],
  ["booked", "تم الحجز"],
  ["not_interested", "غير مهتم"],
  ["no_answer", "لم يرد"],
  ["interested", "مهتم"],
  ["thinking", "يفكر"],
  ["new", "جديد"],
  ["Create", "إنشاء"],
  ["Created", "منشأ"],
  ["Name", "الاسم"],
  ["Capacity", "السعة"],
  ["Group status", "حالة المجموعة"],
  ["Freeze started", "بداية التجميد"],
  ["Freeze finished", "نهاية التجميد"],
  ["Freeze status", "حالة التجميد"],
  ["Full name", "الاسم بالكامل"],
  ["Phone", "الهاتف"],
  ["Email", "البريد الإلكتروني"],
  ["Level", "المستوى"],
  ["Tags", "التصنيفات"],
  ["Class", "الفصل"],
  ["Online / Offline", "أونلاين / أوفلاين"],
  ["Status", "الحالة"],
  ["Total price", "السعر الإجمالي"],
  ["Amount paid", "المبلغ المدفوع"],
  ["Payment date arranged", "تاريخ السداد المتفق عليه"],
  ["Freeze duration", "مدة التجميد"],
  ["Student progress", "حالة تقدم الطالب"],
  ["Continuing", "مستمر"],
  ["Finished level - stopped", "أنهى المستوى - متوقف"],
  ["Payment comment", "تعليق السداد"],
  ["Freeze expired", "انتهى التجميد"],
  ["Schedule", "الجدول"],
  ["Print List", "طباعة القائمة"],
  ["Import", "استيراد"],
  ["Export", "تصدير"],
  ["Search", "بحث"],
  ["Academy System", "نظام إدارة الأكاديمية"],
  ["Dashboard", "لوحة التحكم"],
  ["Students", "الطلاب"],
  ["Student", "الطالب"],
  ["Classes", "الفصول"],
  ["Class", "الفصل"],
  ["Employees Check In", "تسجيل حضور الموظفين"],
  ["Students Check In", "تسجيل حضور الطلاب"],
  ["Student Attendance", "حضور الطلاب"],
  ["Teacher Attendance", "حضور المدرسين"],
  ["HR Performance", "أداء الموظفين"],
  ["Employee KPIs this month", "مؤشرات أداء الموظفين هذا الشهر"],
  ["Sales", "المبيعات"],
  ["Accounts", "الحسابات"],
  ["Treasury", "الخزينة"],
  ["Reports", "التقارير"],
  ["Admin Student Follow Up", "متابعة الطلاب - الإدارة"],
  ["Exams", "الاختبارات"],
  ["Print selected", "طباعة المحدد"],
  ["Student exams and level progression", "اختبارات الطلاب وانتقال المستوى"],
  ["Export filtered", "تصدير المفلتر"],
  ["Import exams", "استيراد الاختبارات"],
  ["Logs", "السجل"],
  ["Textbook inventory", "مخزون الكتب"],
  ["Level test taken", "تم اختبار تحديد المستوى"],
  ["Level result", "نتيجة تحديد المستوى"],
  ["Quiz result", "نتيجة الكويز"],
  ["Main test score", "درجة الاختبار النهائي"],
  ["Next level booked", "تم حجز المستوى التالي"],
  ["Teacher Student Follow Up", "متابعة الطلاب - المدرسين"],
  ["Branches", "الفروع"],
  ["Users", "المستخدمون"],
  ["Files", "الملفات"],
  ["My Leads", "عملائي"],
  ["Add Student", "إضافة طالب"],
  ["Edit Student", "تعديل الطالب"],
  ["Save Student", "حفظ الطالب"],
  ["Save student changes", "حفظ تعديلات الطالب"],
  ["Add Treasury Record", "إضافة سجل خزينة"],
  ["Send Daily Report Now", "إرسال تقرير اليوم الآن"],
  ["Search...", "بحث..."],
  ["Search follow up...", "البحث في المتابعة..."],
  ["Previous", "السابق"],
  ["Next", "التالي"],
  ["No records yet.", "لا توجد سجلات بعد."],
  ["No students found.", "لا يوجد طلاب."],
  ["No students match this filter.", "لا يوجد طلاب يطابقون هذا الفلتر."],
  ["Full name", "الاسم بالكامل"],
  ["Phone", "رقم الهاتف"],
  ["Email", "البريد الإلكتروني"],
  ["Level", "المستوى"],
  ["Tags", "التصنيفات"],
  ["Teacher", "المدرس"],
  ["Mode", "النظام"],
  ["Online", "أونلاين"],
  ["Offline", "أوفلاين"],
  ["Active", "نشط"],
  ["Inactive", "غير نشط"],
  ["Graduated", "متخرج"],
  ["Status", "الحالة"],
  ["Actions", "الإجراءات"],
  ["Edit", "تعديل"],
  ["Delete", "حذف"],
  ["Comment", "تعليق"],
  ["Save comment", "حفظ التعليق"],
  ["Print/PDF", "طباعة / PDF"],
  ["Print payslip", "طباعة كشف المرتب"],
  ["Print Receipt", "طباعة الإيصال"],
  ["Price", "السعر"],
  ["Total price", "السعر الإجمالي"],
  ["Amount paid", "المدفوع"],
  ["Not paid", "المتبقي"],
  ["Payment date", "تاريخ السداد"],
  ["Payment comment", "تعليق السداد"],
  ["Notes", "الملاحظات"],
  ["Date", "التاريخ"],
  ["Type", "النوع"],
  ["Amount", "المبلغ"],
  ["Role", "الوظيفة"],
  ["Employee", "الموظف"],
  ["Pay type", "نوع الأجر"],
  ["Hours", "الساعات"],
  ["Sessions", "الحصص"],
  ["Base", "الأساسي"],
  ["Bonuses", "المكافآت"],
  ["Deductions", "الخصومات"],
  ["Total", "الإجمالي"],
  ["Feedback", "التقييمات"],
  ["Latest Feedback", "آخر تقييم"],
  ["Latest Exam", "آخر اختبار"],
  ["Attendance", "الحضور"],
  ["Save", "حفظ"],
  ["Cancel", "إلغاء"],
  ["Close editor", "إغلاق التعديل"],
  ["Convert to Student", "تحويل إلى طالب"],
  ["Add Note", "إضافة ملاحظة"],
  ["Confirm Import", "تأكيد الاستيراد"],
  ["Import Students", "استيراد الطلاب"],
  ["Export Students", "تصدير الطلاب"],
  ["Import Classes", "استيراد الفصول"],
  ["Export Classes", "تصدير الفصول"],
  ["Sign out", "تسجيل الخروج"],
];

function translate(value: string) {
  return replacements.reduce((result, [english, arabic]) => {
    return result.replace(new RegExp(`\\b${english.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&")}\\b`, "g"), arabic);
  }, value);
}

function translateTree(root: ParentNode) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes: Text[] = [];
  let node: Node | null;
  while ((node = walker.nextNode())) nodes.push(node as Text);
  for (const textNode of nodes) {
    const parent = textNode.parentElement;
    if (!parent || ["SCRIPT", "STYLE", "NOSCRIPT"].includes(parent.tagName)) continue;
    const next = translate(textNode.nodeValue ?? "");
    if (next !== textNode.nodeValue) textNode.nodeValue = next;
  }
  document.querySelectorAll<HTMLElement>("input, textarea, select, button, [aria-label], [title]").forEach((element) => {
    for (const attribute of ["placeholder", "aria-label", "title"]) {
      const value = element.getAttribute(attribute);
      if (value) element.setAttribute(attribute, translate(value));
    }
  });
}

export function ArabicUiTranslator({ lang }: { lang: Lang }) {
  useEffect(() => {
    if (lang !== "ar") return;
    translateTree(document.body);
    const observer = new MutationObserver(() => translateTree(document.body));
    observer.observe(document.body, { childList: true, subtree: true });
    return () => observer.disconnect();
  }, [lang]);
  return null;
}
